Tracs_Portal/Areas/Login/Controllers/PasswordResetController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Tracs.Common.Models;

using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Wangkanai.Detection;
using System.Diagnostics;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using TracsBusinessLogic;
using System.Threading;
using Microsoft.AspNetCore.Routing;

using TRACSPortal.Areas.Login.Services;

namespace TRACSPortal.Areas.Login.Controllers
{
    [Area("Login")]

    public class PasswordResetController : Controller
    {
        private ILoginRepository _loginRepository;
        private IServiceProvider _services;
        private IHostingEnvironment _evn;

        public PasswordResetController(ILoginRepository loginRepository, IServiceProvider services, IHostingEnvironment evn)
        {
            _loginRepository = loginRepository;
            _services = services;
            _evn = evn;
        }
        #region Get Views
        public IActionResult Index()
        {
            
            ViewBag.NoLayout = true;
            ViewBag.IsMobile = Request.Device().Type == DeviceType.Mobile;
            return View();
        }
        public IActionResult ValidateEmail()
        {
            ViewBag.NoLayout = true;
            ViewBag.IsMobile = Request.Device().Type == DeviceType.Mobile;
            return View();
        }
        #endregion

        #region post data
        [HttpPost]
        public ActionResult PasswordResetUpdate()
        {
            string UserId = HttpContext.Session.GetString("UserId");
            string Password = Request.Form["Password"];

            string jsonString = _loginRepository.PasswordResetUpdate(UserId, Password);
            return Content(jsonString, "application/json");

        }
        [HttpPost]
        public ActionResult ValidateEmailUpdate()
        {
            string Email = Request.Form["email"];

            string jsonString = _loginRepository.ValidateEmailUpdate(Email);
            TempData["Email"] = Email;
            TempData["TempPassword"] = true;
            TempData["Password"] = "";
            return Content(jsonString, "application/json");

        }
        #endregion



    }

}

Tracs_Portal/Areas/Login/Views/PasswordReset/Index.cshtml
@{
    Layout = "../Shared/_Layout.cshtml";
    ViewBag.LoginFailed = (ViewBag.LoginFailed ?? false);
    ViewBag.HideLogin = (ViewBag.HideLogin ?? false);
    ViewBag.Title = "RMA TRACS System";
    ViewBag.SubTitle = "Reset Password";
    ViewBag.SubTitle = "Login";
    var IsMobile = ViewBag.IsMobile ?? false;
    var wPercent = IsMobile ? "100" : "40";
    var ColSpan = IsMobile ? "3" : "3";
}

    @using (Html.BeginForm("PasswordResetUpdate", "PasswordReset", FormMethod.Post, new { @class = "center", @id = "frmResetPassword" }))
    {
        var @DisplayLogin = ViewBag.HideLogin ? "display:none" : "";
        <div id="divLogin" class="" style="@DisplayLogin" align="center">

            <table style="width:@wPercent%;" id="tblPasswordReset">

        <tbody>
            <tr class="blank_row">
                <td colspan="2">&nbsp;</td>
            </tr>

            <tr>
                <td align="left">
                    <label style="text-align:right;"><span>New <br />Password:</span> </label>
                </td>
                <td align="left" style="" class="flex-container">
                    @Html.Password("txtNewPassword", null, new { @minlength = "8", @maxlength = "50", @style = "width:80%", @class = "wpcf7-form-control wpcf7-text rma-textfield form-control", @placeholder = "New Password", @required = "", @autofocus = "", @id = "password-txt" })
                    <button id="show_password" class="show-password" style="" type="button">
                        <span class="fa fa-eye icon"></span>
                    </button>
                </td>
                <td align="left"></td>


            </tr>

            <tr>
                <td align="left">
                    <label style="text-align:right;"><span>Confirm <br />Password:</span> </label>
                </td>
                <td align="left" style="" class="flex-container">
                    @Html.Password("txtConfirmPassword", null, new { @style = "width:80%", @class = "wpcf7-form-control wpcf7-text rma-textfield form-control", @placeholder = "Confirm Password", @required = "", @autofocus = "", @id = "confirm-password-txt" })
                    <button id="show_password" class="show-password" style="" type="button">
                        <span class="fa fa-eye icon"></span>
                    </button>
                </td>
                <td align="left"></td>


            </tr>
            <tr class="blank_row">
                <td colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="3">
                    <p id="error_msg" style="font-style:italic;color:white;background-color:red;display:none;text-align:center"> The passwords do not match! </p>
                </td>
            </tr>


            @*<tr class="blank_row">
            <td colspan="2">&nbsp;</td>
        </tr>*@
            <tr>
                <td>&nbsp;</td>
                <td align="left">
                    <button style="width:80%" class="btn btn-lg btn-primary btn-block" type="submit" id="btnResetPassword">Reset my password</button>
                </td>
            </tr>
            @*<tr class="blank_row">
            <td colspan="3">&nbsp;</td>
        </tr>*@
            <tr>
                <td>&nbsp;</td>
                <td align="right">
                    <p id="success_msg" style="font-style:italic;color:white;background-color:forestgreen;display:none;text-align:center"> The password has been changed </p>
                </td>
            </tr>
            <tr>
                <td colspan="@ColSpan" align="center">
                    <a id="btnLogin" href="@Url.Action("Index", "Home")">Login</a>
                </td>
            </tr>
            <tr class="blank_row">
                <td colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="@ColSpan" align="center">
                    <div id="password-details" class="self hidden" align="center">
                        <div style="width:100%">
                            <p>Password must have the following:</p>
                            <ul>
                                <li>At least 8 characters</li>
                                <li>
                                    1 uppercase
                                    letter, i.e. A
                                </li>
                                <li>1 lowercase letter, i.e. a</li>
                                <li>1 digit, i.e. 1</li>
                                <li>1 special character (#?!@@$%^&amp;*_)</li>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>



    
    <br />
</div>


    }
    
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>
    <script src="~/js/Custom/Login/bootbox.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script src="~/js/Custom/ParabitScripts/password_validation.js"></script>
<script>
    $(document).ready(function () {
        $('.btn-primary').css('background-color', '#F57B20')
        $("#password-txt").trigger("focus");
        //ValidatePasswordMain();
    });

    $("#frmResetPassword").validate({
        errorClass: 'validate-error',
        errorPlacement: function (error, element) {
            //var regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@@#\$%\^&\*%?])(?=.{8,16}).*/g;
            var newCell = $('<td> </td>');
            var newRow = $('<tr> </tr>');
            newCell.appendTo(newRow);
            newCell = $('<td align="right"> </td>')
            error.css("width", "90%");
            error.attr("align", "left");
            error.appendTo(newCell);
            newCell.appendTo(newRow);
            newRow.insertAfter(element.closest('tr'));
            $("input").each(function () {
                $(this).attr("autocomplete", "none");
            });
        },
        
    });
    
    $("#frmResetPassword").submit(function (e) {
        e.preventDefault();
        if (!ValidatePassword())
            return;
        var new_pass = $('#password-txt').val();
        var confirm_pass = $('#confirm-password-txt').val();
        if (new_pass.length == 0 || confirm_pass.length == 0) {
            $("#error_msg").text("Password cannot be blank");
            $("#success_msg").hide();
            $("#error_msg").show();
            return;
        }
        if (new_pass != confirm_pass) {
            $("#error_msg").text("Passwords do not match");
            $("#success_msg").hide();
            $("#error_msg").show();
            return;
        }
        
        $("#error_msg").hide();
        $("#success_msg").hide();
        $.ajax({
            type: "POST",
            url: '@Url.Action("PasswordResetUpdate", "PasswordReset")',
            data: { password: new_pass },
            async: false,
            success: function (result) {
                var status = result.status;
                var message = result.message;
                if (status == 0) {
                    $("#error_msg").text(message);
                    $("#error_msg").show();
                }
                else {
                    $("#success_msg").text(message);
                    //$("#success_msg").show();
                    var location = '@Url.Action("Index", "Home")';
                    changeToTapToDismissToastr();
                    changeFeedbackMessage('success', message, '',
                        '<br /><br /><br /><button onclick = "href" type="button" class="para-btn clear">Login</button>'.replace('href', 'window.location.href = \'' + location +'\'')
                    );
                }

            },
            error: function (request, status, error) {
                $("#error_msg").text(error);
                $("#error_msg").show();
            }

        });
    });
</script>

Tracs_Portal/Areas/Login/Views/PasswordReset/ValidateEmail.cshtml
@{
    ViewBag.Title = "RMA TRACS System";
    ViewBag.SubTitle = "Forgot Password";
    Layout = "../Shared/_Layout.cshtml";
    var IsMobile = ViewBag.IsMobile ?? false;
    var wPercent = IsMobile ? "100" : "40";
    var ColSpan = IsMobile ? "3" : "3";
}

@using (Html.BeginForm("ValidateEmailUpdate", "Home", FormMethod.Post, new { @class = "center", @id = "frmValidateEmail" }))
{

    <div id="divForgotPassword" class="m-y12" align="center">

        <br />

        <table style="width:@wPercent%; align:center">
            @*<tr>
                    <td colspan="3" align="center">
                        <h1 class="h3 mb-3 font-weight-bold" style="font-size:large;text-decoration:underline ">Validate E-Mail</h1>
                    </td>

                </tr>*@
            <tr class="blank_row">
                <td colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="2">
                    <p id="lblReturnMessage" style="text-align:center;font-style:italic;color:white;background-color:red; display:none;">  </p>
                </td>
            </tr>
            <tr>
                <td width="20%" align="left">
                    <label style="display:block;text-align:left"><span>E-Mail:</span> </label>
                </td>
                <td width="60%" align="right">
                    @Html.TextBox("txtEmail", null, new { @style = "float:right; width:100%", @type = "email", @class = "wpcf7-form-control wpcf7-text rma-textfield form-control", @placeholder = "email", @required = "", @autofocus = "" })
                </td>
                <td align="left"></td>

            </tr>
            <tr class="blank_row">
                <td colspan="2">&nbsp;</td>
            </tr>

            <tr>
                <td>&nbsp;</td>
                <td align="right">
                    <button class="btn btn-lg btn-primary btn-block" type="submit" id="btnValidateEmail">Request Temporary Password</button>
                </td>

            </tr>
            <tr class="blank_row">
                <td colspan="2">&nbsp;</td>
            </tr>

            <tr>
                <td colspan="@ColSpan" align="center">
                    <a id="btnLogin" href="@Url.Action("Index", "Home")">Login</a>
                </td>

            </tr>
        </table>
    </div>


}



<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>

<script>
    $("#frmValidateEmail").validate({
        errorClass: 'validate-error',
        errorPlacement: function (error, element) {
            var newCell = $('<td> </td>');
            var newRow = $('<tr> </tr>');
            newCell.appendTo(newRow);
            newCell = $('<td align="right"> </td>')
            error.css("width", "90%");
            error.attr("align", "left");
            error.appendTo(newCell);
            newCell.appendTo(newRow);
            newRow.insertAfter(element.closest('tr'));


        }
    });



    $(document).ready(function () {
        $('.btn-primary').css('background-color', '#F57B20')
        $("input").each(function () {
            $(this).attr("autocomplete", "none");
        });
    });
    $("#frmValidateEmail").submit(function (e) {
        e.preventDefault();
        if ($("#frmValidateEmail").find(".error:visible").length > 0 || $(this).find(".validate-error:visible").length > 0)
            return;
        $("#lblReturnMessage").hide();
        $("#btnLogin").hide();
        var sEmail = $('#txtEmail').val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ValidateEmailUpdate", "PasswordReset")',
            data: { email: $('#txtEmail').val()},
            async: false,
            success: function (result) {
                var message = result.message;
                var status = result.status;
                if (status == 1) {
                    //$("#lblReturnMessage").css('background-color', 'forestgreen');
                    var location = '@Url.Action("Index", "Home")';
                    changeToTapToDismissToastr();
                    changeFeedbackMessage('success', message, '',
                        '<br /><br /><br /><button onclick = "href" type="button" class="para-btn clear">Login</button>'.replace('href', 'window.location.href = \'' + location + '\'')
                    );
                }
                else
                    $("#lblReturnMessage").text(message);
                    $("#lblReturnMessage").css('background-color', 'red');
                    $("#lblReturnMessage").show();
                    $("#btnLogin").show();
                    //changeFeedbackMessage('error', message)

            },
            error: function (request, status, error) {
                alert(error);
            }

        });


    });


</script>